# Generated by Django 5.0.4 on 2025-11-11 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='lecture',
            new_name='lecturer',
        ),
    ]
