# Generated by Django 5.0.4 on 2025-11-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_student_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureProfile',
            new_name='LecturerProfile',
        ),
    ]
