# Generated by Django 5.0.4 on 2025-12-08 19:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name (2–120 characters).', max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth_date', models.DateField(default='1900-01-01', help_text='Date of birth. Defaults to 1900-01-01.')),
                ('nationality', models.CharField(default='Unknown', help_text="Country of origin. Defaults to 'Unknown'.", max_length=50)),
                ('is_awarded', models.BooleanField(default=False, help_text='Indicates whether this entity has received awards.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Automatically updated when the record is modified.')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name (2–120 characters).', max_length=120, validators=[django.core.validators.MinLengthValidator(2)])),
                ('birth_date', models.DateField(default='1900-01-01', help_text='Date of birth. Defaults to 1900-01-01.')),
                ('nationality', models.CharField(default='Unknown', help_text="Country of origin. Defaults to 'Unknown'.", max_length=50)),
                ('years_of_experience', models.SmallIntegerField(default=0, help_text='Years of directing experience (minimum 0).', validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_awarded', models.BooleanField(default=False, help_text='Indicates whether this entity has received awards.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Automatically updated when the record is modified.')),
                ('title', models.CharField(help_text='Title (5–150 characters).', max_length=150, validators=[django.core.validators.MinLengthValidator(5)])),
                ('release_date', models.DateField(help_text='Release date of the movie.')),
                ('storyline', models.TextField(blank=True, help_text='Optional short summary. Can be empty/null.', null=True)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Other', 'Other')], default='Other', help_text='Genre: Action, Comedy, Drama, or Other.', max_length=6)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Rating between 0.0 and 10.0 (one decimal).', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('is_classic', models.BooleanField(default=False, help_text='Indicates whether the movie is considered a classic.')),
                ('actors', models.ManyToManyField(blank=True, help_text='All participating actors (many-to-many).', related_name='movies', to='main_app.actor')),
                ('director', models.ForeignKey(help_text='Director of this movie (deleting director deletes the movie).', on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='main_app.director')),
                ('starring_actor', models.ForeignKey(blank=True, help_text='Main actor (nullable; becomes NULL if actor is deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starred_movies', to='main_app.actor')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
